Заменила реглярное выражение для пути.
technology16/pgpass pull request #4
Opened 2020-06-25 11:50 UTC by AxelCat

2020-06-26 10:53 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +					if (pathParts.find()) {
лучше `matches()`, файнд ищет вхождение в строке, матчез проверяет всю строку на совпадение

еще перенеси условие следующего ифа сюда же, лишняя вложенность уберется

2020-06-30 10:30 UTC, Endeavourl requested changes

2020-06-30 10:30 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +    public static String getUnEscape(String line) {
лучше назвать просто `unescape`

2020-06-30 10:30 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +        char[] lineChars = line.toCharArray();
лучше проходить по самой строке без копирования символов в отдельный массив  
вместо `chars[i]` использовать `String.charAt(i)`

2020-06-30 10:30 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +        char backslash = '\\';
необязательно выделять переменные под такие константы, я бы убрал

2020-06-30 10:30 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +                if (lineChars[i + 1] == doubleDot) {
нужно перед проверкой следующего символа проверить, что ты не в конце строки

2020-06-30 10:30 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +                    if (lineChars[i + 1] == backslash) {
здесь не так, первый ты копируешь оба слэша, нужно пропустить или текущий или следующий  
тест тоже проверяет неправильный вараинт

2020-06-30 11:33 UTC, AxelCat commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +                    if (lineChars[i + 1] == backslash) {
а почему оба слэша копировать нужно?

2020-07-02 06:34 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +                if (i < line.length()) {
ты не можешь так сравнивать, индексы начинаются с 0, а длина с 1  
правильно - `i + 1 < length`

2020-07-02 06:34 UTC, Endeavourl commented on src/main/java/ru/taximaxim/pgpass/PgPass.java
> +                    if (line.charAt(i + 1) == ':') {
оба ифа теперь одинаковые, можно их объединить

т.к. ты сравниваешь примитивы (символы) - еще удобнее сделать через switch  
```
switch (charAt)
case '\\':
case':':
...
```

2020-07-02 10:16 UTC, Endeavourl approved these changes

2020-07-02 10:18 UTC, merged